### ISSUE TITLE
No internet connection Android 10

### ISSUE THREAD

**Issue by NizarETH** [Jagrajsinghji/wifi_network_specifier_connect#1]
It's connect to hotspot in Android 10, but without Internet access

**Comment by Jagrajsinghji** [comment]
It can not check whether there is an active internet connection or not. For that you can ping your own server or any other site and if you get the result back then you can say there is an active internet connection.

**Comment by NizarETH** [comment]
Yes, that what I did, I open my browser to check, by the way I look for days how to connect to hotspot in Android 10 with Internet access but nothing work for me, my question in StackOverFlow if you can help me and help all developers.
[https://stackoverflow.com/questions/63124728/connect-to-wifi-in-android-q-programmatically](https://stackoverflow.com/questions/63124728/connect-to-wifi-in-android-q-programmatically)

**Comment by Jagrajsinghji** [comment]
I would say if you want to connect to wifi on Q and above then you need Wi-Fi network specifier.
If you want to check for internet connectivity then within from the same application you need to make a http request to a server or site and check  your response. You can't check it by opening another application or browser because the scope of connected wifi is local to your app. In case you close your app then wifi gets disconnected.
I hope I explained it well.

**Comment by NizarETH** [comment]
@Jagrajsinghji Yes I get it, but why the app that I add in the link don't have this limitation of scope ? you can look ? I installed a couple days ago, I connect to my hotspot I leave the app and I still connected to internet, it's really weird.
thank's

**Comment by Jagrajsinghji** [comment]
If you can do one thing for me please,
Could you just forget your hotspot configuration from wifi settings and then try connecting it by using that app you're talking and then close the app, and check if you're still connected to your hotspot or not?

What I think is happening with you is the configuration is saved on your phone previously and the app connects to it normally and when you close the app it disconnect the wifi but due to previously saved configuration the system again connects to it.

**Comment by NizarETH** [comment]
ok, I'll try it, sorry I wasn't near to my computer

**Comment by NizarETH** [comment]
I tried multiple time, I debug my a lot of code too, for Android Q, as you said Wi-Fi network specifier keep the scope of internet access limited only inside the app, If you leave the app which you trigger the connection to a hotspot, then, you will not have internet access.
thank's

**Comment by Jagrajsinghji** [comment]
Yeah, so if you need to check internet ping server and check response from within your app. That's the best I can think of. I am closing this issue right now. Feel free to open it if you have any questions.
